name: order-service

on:
  push:
    branches: [main]
    paths:
      - "services/order-service/**"
      - ".github/workflows/order-service.yml"
      - ".github/workflows/_build-service.yml"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  ci:
    uses: ./.github/workflows/_build-service.yml
    with:
      service: order-service
